# cau noi cho IMU
- ros_topic_name: "/simple_robot/imu"
  gz_topic_name: "/simple_robot/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# cau noi cho Joint state (encoder)
- ros_topic_name: "/simple_robot/joint_states"
  gz_topic_name: "/simple_robot/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# cau noi truyen luc banh trai
- ros_topic_name: "/model/simple_robot/joint/left_wheel_joint/cmd_force"
  gz_topic_name: "/model/simple_robot/joint/left_wheel_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# cau noi truyen luc banh phai
- ros_topic_name: "/model/simple_robot/joint/right_wheel_joint/cmd_force"
  gz_topic_name: "/model/simple_robot/joint/right_wheel_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
  
# Cầu nối Thời gian (Đồng bộ nhịp đập Gazebo và ROS 2)
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS